name: Build and publish a Docker image to ghcr.io
on:
  release:
    types: [published]

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Containerfile

      - name: Tag latest
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/${IMAGE_NAME}:${VERSION} ghcr.io/${IMAGE_NAME}:latest
          docker push ghcr.io/${IMAGE_NAME}:latest
